INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2117', '84', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2118', '84', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2119', '84', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2120', '84', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2121', '84', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2122', '84', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2123', '84', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2124', '84', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2182', '87', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2125', '84', '관리감독자 일일안전점검', '위험작업조치', '용접,용단,연마 , 절단작업시 소화기구, 비산 방지, 환기 조치여부', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2126', '84', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2127', '84', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2128', '85', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2129', '85', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2130', '85', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2131', '85', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2132', '85', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2133', '85', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2134', '85', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2135', '85', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2136', '85', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2137', '85', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2138', '85', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2139', '85', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2140', '85', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2141', '85', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2142', '85', '관리감독자 일일안전점검', '공통', '설비, 기계, 기구 등 점검 후 조치', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2143', '85', '관리감독자 일일안전점검', '공통', '각 종 기계기구의 이상 유무', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2144', '85', '관리감독자 일일안전점검', '공통', '작업장 정리정돈, 통로확보 개구부 확인 점검결과', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2145', '85', '관리감독자 일일안전점검', '중량물취급작업 크레인', '올바른 자세, 복장 및 보호구착용 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2146', '85', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2147', '85', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2148', '85', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2149', '85', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2150', '85', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2151', '85', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2152', '85', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2153', '85', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2154', '85', '관리감독자 일일안전점검', '위험작업조치', '용접,용단,연마 , 절단작업시 소화기구, 비산 방지, 환기 조치여부', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2155', '85', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2156', '85', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2157', '86', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2158', '86', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2159', '86', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2160', '86', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2161', '86', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2162', '86', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2163', '86', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2164', '86', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2165', '86', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2166', '86', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2167', '86', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2168', '86', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2169', '86', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2170', '86', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2171', '86', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2172', '86', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2173', '86', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2174', '86', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2175', '86', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2176', '86', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2177', '86', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2178', '86', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2179', '86', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2180', '87', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2181', '87', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2183', '87', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2184', '87', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2185', '87', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2186', '87', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2187', '87', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2188', '87', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2189', '87', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2190', '87', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2191', '87', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2192', '87', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2193', '87', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2194', '87', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2195', '87', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2196', '87', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2197', '87', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2198', '87', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2199', '87', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2200', '87', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2201', '87', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2202', '87', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2203', '88', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2204', '88', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2205', '88', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2206', '88', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2207', '88', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2208', '88', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2209', '88', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2210', '88', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2211', '88', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2212', '88', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2213', '88', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2214', '88', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2215', '88', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2216', '88', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2217', '88', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2218', '88', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2219', '88', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2220', '88', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2221', '88', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2222', '88', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태, 하부 작업 여부', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2223', '88', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2224', '88', '관리감독자 일일안전점검', '공기압축기', '드레인밸브, 압력방출장치, 언로드밸브, 윤활유, 덮개 이상 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2225', '88', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2226', '88', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2227', '88', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2228', '88', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2229', '88', '관리감독자 일일안전점검', '위험작업조치', '용접,용단,연마 , 절단작업시 소화기구, 비산 방지, 환기 조치여부', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2230', '88', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2231', '88', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2232', '89', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2233', '89', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2234', '89', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2235', '89', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2236', '89', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2237', '89', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2238', '89', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2239', '89', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2240', '89', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2241', '89', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2242', '89', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2243', '89', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2244', '89', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2245', '89', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2246', '89', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2247', '89', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2248', '89', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2249', '89', '관리감독자 일일안전점검', '사무실안전', '파티션이나 그 밖에 넘어질 위험 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2250', '89', '관리감독자 일일안전점검', '사무실안전', '끼이거나 부딪힐 수 있는 열린 서랍 등이 있는지 여부', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2251', '89', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2252', '89', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2253', '89', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2254', '89', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2255', '90', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2256', '90', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2257', '90', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2258', '90', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2259', '90', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2260', '90', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2261', '90', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2262', '90', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2263', '90', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2264', '90', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2265', '90', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2266', '90', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2267', '90', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2268', '90', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2269', '90', '관리감독자 일일안전점검', '공통', '설비, 기계, 기구 등 점검 후 조치', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2270', '90', '관리감독자 일일안전점검', '공통', '각 종 기계기구의 이상 유무', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2271', '90', '관리감독자 일일안전점검', '공통', '작업장 정리정돈, 통로확보 개구부 확인 점검결과', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2272', '90', '관리감독자 일일안전점검', '중량물취급작업 크레인', '올바른 자세, 복장 및 보호구착용 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2273', '90', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2274', '90', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2275', '90', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2276', '90', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2277', '90', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2278', '90', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2279', '90', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2280', '90', '관리감독자 일일안전점검', '위험작업조치', '전단기, 절곡기 등의 방호장치의 기능', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2281', '90', '관리감독자 일일안전점검', '위험작업조치', '클러치, 브레이크, 금형, 고정볼트, 칼날, 테이블 등의 상태', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2282', '90', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2283', '90', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2284', '91', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2285', '91', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2286', '91', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2287', '91', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2288', '91', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2289', '91', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2290', '91', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2291', '91', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2292', '91', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2293', '91', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2294', '91', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2295', '91', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2296', '91', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2297', '91', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2298', '91', '관리감독자 일일안전점검', '공통', '설비, 기계, 기구 등 점검 후 조치', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2299', '91', '관리감독자 일일안전점검', '공통', '각 종 기계기구의 이상 유무', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2300', '91', '관리감독자 일일안전점검', '공통', '작업장 정리정돈, 통로확보 개구부 확인 점검결과', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2301', '91', '관리감독자 일일안전점검', '중량물취급작업 크레인', '올바른 자세, 복장 및 보호구착용 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2302', '91', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2303', '91', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2304', '91', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2305', '91', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2306', '91', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2307', '91', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2308', '91', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2309', '91', '관리감독자 일일안전점검', '위험작업조치', '전단기, 절곡기 등의 방호장치의 기능', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2310', '91', '관리감독자 일일안전점검', '위험작업조치', '클러치, 브레이크, 금형, 고정볼트, 칼날, 테이블 등의 상태', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2311', '91', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2312', '91', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2313', '92', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2314', '92', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2315', '92', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2316', '92', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2317', '92', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2318', '92', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2319', '92', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2320', '92', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2321', '92', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2322', '92', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2323', '92', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2324', '92', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2325', '92', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2326', '92', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2327', '92', '관리감독자 일일안전점검', '공통', '설비, 기계, 기구 등 점검 후 조치', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2328', '92', '관리감독자 일일안전점검', '공통', '각 종 기계기구의 이상 유무', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2329', '92', '관리감독자 일일안전점검', '공통', '작업장 정리정돈, 통로확보 개구부 확인 점검결과', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2330', '92', '관리감독자 일일안전점검', '중량물취급작업 크레인', '올바른 자세, 복장 및 보호구착용 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2331', '92', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2332', '92', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2333', '92', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2334', '92', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2335', '92', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2336', '92', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2337', '92', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2338', '92', '관리감독자 일일안전점검', '위험작업조치', '전단기, 절곡기 등의 방호장치의 기능', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2339', '92', '관리감독자 일일안전점검', '위험작업조치', '클러치, 브레이크, 금형, 고정볼트, 칼날, 테이블 등의 상태', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2340', '92', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2341', '92', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2342', '93', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2343', '93', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2344', '93', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2345', '93', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2346', '93', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2347', '93', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2348', '93', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2349', '93', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2350', '93', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2351', '93', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2352', '93', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2353', '93', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2354', '93', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2355', '93', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2356', '93', '관리감독자 일일안전점검', '공통', '설비, 기계, 기구 등 점검 후 조치', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2357', '93', '관리감독자 일일안전점검', '공통', '각 종 기계기구의 이상 유무', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2358', '93', '관리감독자 일일안전점검', '공통', '작업장 정리정돈, 통로확보 개구부 확인 점검결과', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2359', '93', '관리감독자 일일안전점검', '중량물취급작업 크레인', '올바른 자세, 복장 및 보호구착용 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2360', '93', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2361', '93', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2362', '93', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2363', '93', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2364', '93', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2365', '93', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2366', '93', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2367', '93', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2368', '93', '관리감독자 일일안전점검', '위험작업조치', '용접,용단,연마 , 절단작업시 소화기구, 비산 방지, 환기 조치여부', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2369', '93', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2370', '93', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2371', '94', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2372', '94', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2373', '94', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2374', '94', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2375', '94', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2376', '94', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2377', '94', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2378', '94', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2379', '94', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2380', '94', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2381', '94', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2382', '94', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2383', '94', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2384', '94', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2385', '94', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2386', '94', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2387', '94', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2388', '94', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2389', '94', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2390', '94', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2391', '94', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2392', '94', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2393', '94', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2394', '95', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2395', '95', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2396', '95', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2397', '95', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2398', '95', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2399', '95', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2400', '95', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2401', '95', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2402', '95', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2403', '95', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('955', '39', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('956', '39', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('957', '39', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('958', '39', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('959', '39', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('960', '39', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('961', '39', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('962', '39', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('963', '39', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('964', '39', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('965', '39', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('966', '39', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('967', '39', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('968', '39', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('969', '39', '관리감독자 일일안전점검', '공통', '설비, 기계, 기구 등 점검 후 조치', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('970', '39', '관리감독자 일일안전점검', '공통', '각 종 기계기구의 이상 유무', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('971', '39', '관리감독자 일일안전점검', '공통', '작업장 정리정돈, 통로확보 개구부 확인 점검결과', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('972', '39', '관리감독자 일일안전점검', '중량물취급작업 크레인', '올바른 자세, 복장 및 보호구착용 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('973', '39', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('974', '39', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('975', '39', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('976', '39', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('977', '39', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('978', '39', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('979', '39', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('980', '39', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('981', '39', '관리감독자 일일안전점검', '위험작업조치', '용접,용단,연마 , 절단작업시 소화기구, 비산 방지, 환기 조치여부', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('982', '39', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2529', '101', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2404', '95', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2405', '95', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('983', '39', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1065', '43', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1066', '43', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1067', '43', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1068', '43', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1069', '43', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1070', '43', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1071', '43', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1072', '43', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1073', '43', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1074', '43', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1075', '43', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1076', '43', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1077', '43', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1078', '43', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1079', '43', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1080', '43', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1081', '43', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1082', '43', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1083', '43', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1084', '43', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1085', '43', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1086', '43', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1087', '43', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1117', '45', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1118', '45', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1119', '45', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1120', '45', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1121', '45', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1122', '45', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1123', '45', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1124', '45', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1125', '45', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1126', '45', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1127', '45', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1128', '45', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1129', '45', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1130', '45', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1131', '45', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1132', '45', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1133', '45', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1134', '45', '관리감독자 일일안전점검', '사무실안전', '파티션이나 그 밖에 넘어질 위험 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1135', '45', '관리감독자 일일안전점검', '사무실안전', '끼이거나 부딪힐 수 있는 열린 서랍 등이 있는지 여부', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1136', '45', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1137', '45', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1138', '45', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1139', '45', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1163', '47', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1164', '47', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1165', '47', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1166', '47', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1167', '47', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1168', '47', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1169', '47', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1170', '47', 'TBM', '교육', '사고사례 공유 - 타사 사고사례 및 아차 사고사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1171', '47', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1172', '47', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1173', '47', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1174', '47', '관리감독자 일일안전점검', '공통', '담당직원 작업시 안전상태 확인', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1175', '47', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('2530', '101', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('775', '31', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('776', '31', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('777', '31', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('778', '31', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('779', '31', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('780', '31', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('781', '31', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('782', '31', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('783', '31', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('784', '31', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('785', '31', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('786', '31', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('787', '31', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('788', '31', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('789', '31', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('790', '31', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('791', '31', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('792', '31', '관리감독자 일일안전점검', '사무실안전', '파티션이나 그 밖에 넘어질 위험 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('793', '31', '관리감독자 일일안전점검', '사무실안전', '끼이거나 부딪힐 수 있는 열린 서랍 등이 있는지 여부', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('794', '31', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('795', '31', '관리감독자 일일안전점검', '테스트작업', '돌가루 등 비산 위험이 있는곳에서 보안경 착용 여부', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('796', '31', '관리감독자 일일안전점검', '테스트작업', '작업자가 낙하물 범위 밖으로 있는지 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('797', '31', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('942', '38', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('943', '38', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('944', '38', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('945', '38', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('946', '38', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('947', '38', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('948', '38', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('949', '38', 'TBM', '교육', '사고사례 공유 - 타사 사고사례 및 아차 사고사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('950', '38', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('951', '38', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('952', '38', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('953', '38', '관리감독자 일일안전점검', '공통', '담당직원 작업시 안전상태 확인', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('954', '38', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1088', '44', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1089', '44', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1090', '44', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1091', '44', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1092', '44', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1093', '44', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1094', '44', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1095', '44', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1096', '44', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1097', '44', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1098', '44', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1099', '44', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1100', '44', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1101', '44', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1102', '44', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1103', '44', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1104', '44', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1105', '44', '관리감독자 일일안전점검', '중량물취급작업 크레인', '주행로 상측 및 트롤리가 횡행하는 레일, 와이어 통하는 곳의 상태', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1106', '44', '관리감독자 일일안전점검', '중량물취급작업 크레인', '권과방지장치ㆍ브레이크ㆍ클러치 및 운전장치의 기능', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1107', '44', '관리감독자 일일안전점검', '중량물취급작업 크레인', '슬링, 와이어로프등의 이상 유무 및 매달린 상태, 하부 작업 여부', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1108', '44', '관리감독자 일일안전점검', '중량물취급작업 크레인', '인양물 하부 작업 여부', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1109', '44', '관리감독자 일일안전점검', '공기압축기', '드레인밸브, 압력방출장치, 언로드밸브, 윤활유, 덮개 이상 여부', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1110', '44', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1111', '44', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '240');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1112', '44', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '250');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1113', '44', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '260');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1114', '44', '관리감독자 일일안전점검', '위험작업조치', '용접,용단,연마 , 절단작업시 소화기구, 비산 방지, 환기 조치여부', '270');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1115', '44', '관리감독자 일일안전점검', '위험작업조치', '통전 전류, 접지 상태, 가스, 유해물질 등 작업환경 점검', '280');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1116', '44', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '290');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1140', '46', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1141', '46', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1142', '46', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1143', '46', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1144', '46', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1145', '46', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1146', '46', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1147', '46', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1148', '46', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1149', '46', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1150', '46', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1151', '46', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1152', '46', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1153', '46', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1154', '46', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1155', '46', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1156', '46', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1157', '46', '관리감독자 일일안전점검', '사무실안전', '파티션이나 그 밖에 넘어질 위험 여부', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1158', '46', '관리감독자 일일안전점검', '사무실안전', '끼이거나 부딪힐 수 있는 열린 서랍 등이 있는지 여부', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1159', '46', '관리감독자 일일안전점검', '위험작업조치', '고소작업시 안전모 착용, 안전고리 체결 유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1160', '46', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1161', '46', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('1162', '46', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('798', '32', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('799', '32', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('800', '32', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('801', '32', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('802', '32', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('803', '32', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('804', '32', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('805', '32', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('806', '32', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('807', '32', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('808', '32', '위험평가 및 개선대책', '위험예지훈련', '크레인, 리프트, 지게차 등 설비에 대한 위험', '110');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('809', '32', '위험평가 및 개선대책', '위험예지훈련', '작업장 개구부, 고소작업 등에 대한 위험', '120');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('810', '32', '위험평가 및 개선대책', '위험예지훈련', '그라인더, 인양달기구 등 사용하는 기구,도구에 대한 위험', '130');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('811', '32', '위험평가 및 개선대책', '확인', '지적확인 - 중점 위험요인 선정 구호 제창 (중점도 높은 사항으로 선정)', '140');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('812', '32', '관리감독자 일일안전점검', '공통', '사무실 및 작업장 정리정돈', '150');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('813', '32', '관리감독자 일일안전점검', '공통', '현장 출입 시 안전보호구 착용 유무(안전모, 안전화 등)', '160');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('814', '32', '관리감독자 일일안전점검', '공통', '종사자의 건강상태 이상유무', '170');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('815', '32', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 작업시 올바른 자세 및 복장 교육', '180');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('816', '32', '관리감독자 일일안전점검', '중량물운반 작업', '중량물 취급시 바닥의 상태 등 운반환경 점검', '190');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('817', '32', '관리감독자 일일안전점검', '지게차 하역운반기계', '안전벨트 착용 상태 및 작업장내 과속, 급선회, 급출발 등 이상유무', '200');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('818', '32', '관리감독자 일일안전점검', '지게차 하역운반기계', '제동장치 및 조종장치, 하역장치 및 유압장치 기능의 이상유무', '210');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('819', '32', '관리감독자 일일안전점검', '지게차 하역운반기계', '전조등ㆍ후미등ㆍ방향지시기 및 경보장치, 바퀴 기능의 이상유무', '220');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('820', '32', '인원관리', '시작/종료', '작업시작 및 종료 시, 담당직원의 투입 시/퇴장 시 인원 점검', '230');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('821', '33', 'TBM', '도입', '아침 조회 - 아침 체조 스트레칭', '10');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('822', '33', 'TBM', '점검', '건강/복장/보호구 - 음주상태', '20');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('823', '33', 'TBM', '점검', '건강/복장/보호구 - 건강상태', '30');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('824', '33', 'TBM', '점검', '건강/복장/보호구 - 복장', '40');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('825', '33', 'TBM', '점검', '건강/복장/보호구 - 보호구', '50');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('826', '33', 'TBM', '지시', '작업내용 전파 - 생산회의', '60');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('827', '33', 'TBM', '지시', '작업내용 전파 - 금일 안전작업 내용지시', '70');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('828', '33', '위험평가 및 개선대책', '위험예지훈련', '각 팀원 최근 아차사고 사례 공유', '80');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('829', '33', '위험평가 및 개선대책', '위험예지훈련', '작업장소 등 환경에 대한 위험', '90');
INSERT INTO "TemplateItems" ("id", "templateId", "category", "subCategory", "description", "displayOrder") VALUES ('830', '33', '위험평가 및 개선대책', '위험예지훈련', '입고, 출고, 조립, 가공 등 공정 순서(작업방법)에 대한 위험', '100');