INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."TeamEquipments"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "TeamEquipments_pkey" PRIMARY KEY (id);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TeamMembers TeamMembers_pkey; Type: CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."TeamMembers"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "TeamMembers_pkey" PRIMARY KEY (id);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Teams Teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Teams"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Teams_pkey" PRIMARY KEY (id);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TemplateItems TemplateItems_pkey; Type: CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."TemplateItems"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "TemplateItems_pkey" PRIMARY KEY (id);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: UserAssessment UserAssessment_pkey; Type: CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."UserAssessment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "UserAssessment_pkey" PRIMARY KEY (id);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: UserProgress UserProgress_pkey; Type: CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."UserProgress"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "UserProgress_pkey" PRIMARY KEY (id);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."User"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "User_pkey" PRIMARY KEY (id);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public.user_sessions');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (sid);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: AbsenceRecords_memberId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "AbsenceRecords_memberId_idx" ON public."AbsenceRecords" USING btree ("memberId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: AbsenceRecords_reportId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "AbsenceRecords_reportId_idx" ON public."AbsenceRecords" USING btree ("reportId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests_approverId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ApprovalRequests_approverId_idx" ON public."ApprovalRequests" USING btree ("approverId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests_reportId_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "ApprovalRequests_reportId_key" ON public."ApprovalRequests" USING btree ("reportId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests_requestedAt_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ApprovalRequests_requestedAt_idx" ON public."ApprovalRequests" USING btree ("requestedAt");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests_requesterId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ApprovalRequests_requesterId_idx" ON public."ApprovalRequests" USING btree ("requesterId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests_status_approverId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ApprovalRequests_status_approverId_idx" ON public."ApprovalRequests" USING btree (status, "approverId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests_status_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ApprovalRequests_status_idx" ON public."ApprovalRequests" USING btree (status);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Assessment_courseId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Assessment_courseId_idx" ON public."Assessment" USING btree ("courseId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment_commentId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Attachment_commentId_idx" ON public."Attachment" USING btree ("commentId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment_courseId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Attachment_courseId_idx" ON public."Attachment" USING btree ("courseId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment_noticeId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Attachment_noticeId_idx" ON public."Attachment" USING btree ("noticeId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment_reportDetailId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Attachment_reportDetailId_idx" ON public."Attachment" USING btree ("reportDetailId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Certificate_certificateNumber_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "Certificate_certificateNumber_key" ON public."Certificate" USING btree ("certificateNumber");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Certificate_courseId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Certificate_courseId_idx" ON public."Certificate" USING btree ("courseId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Certificate_userId_courseId_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "Certificate_userId_courseId_key" ON public."Certificate" USING btree ("userId", "courseId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Certificate_userId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Certificate_userId_idx" ON public."Certificate" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ChecklistTemplates_teamId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ChecklistTemplates_teamId_idx" ON public."ChecklistTemplates" USING btree ("teamId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Comment_authorId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Comment_authorId_idx" ON public."Comment" USING btree ("authorId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Comment_noticeId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Comment_noticeId_idx" ON public."Comment" USING btree ("noticeId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: DailyReports_reportDate_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "DailyReports_reportDate_idx" ON public."DailyReports" USING btree ("reportDate");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: DailyReports_site_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "DailyReports_site_idx" ON public."DailyReports" USING btree (site);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: DailyReports_site_reportDate_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "DailyReports_site_reportDate_idx" ON public."DailyReports" USING btree (site, "reportDate");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: DailyReports_teamId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "DailyReports_teamId_idx" ON public."DailyReports" USING btree ("teamId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: DailyReports_teamId_reportDate_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "DailyReports_teamId_reportDate_idx" ON public."DailyReports" USING btree ("teamId", "reportDate");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: EmailLogs_emailType_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "EmailLogs_emailType_idx" ON public."EmailLogs" USING btree ("emailType");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: EmailLogs_recipientEmail_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "EmailLogs_recipientEmail_idx" ON public."EmailLogs" USING btree ("recipientEmail");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: EmailLogs_recipientId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "EmailLogs_recipientId_idx" ON public."EmailLogs" USING btree ("recipientId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: EmailLogs_sentAt_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "EmailLogs_sentAt_idx" ON public."EmailLogs" USING btree ("sentAt");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: EmailLogs_status_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "EmailLogs_status_idx" ON public."EmailLogs" USING btree (status);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Factories_code_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Factories_code_idx" ON public."Factories" USING btree (code);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Factories_code_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "Factories_code_key" ON public."Factories" USING btree (code);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Holidays_date_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Holidays_date_idx" ON public."Holidays" USING btree (date);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Holidays_date_site_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "Holidays_date_site_key" ON public."Holidays" USING btree (date, site);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Holidays_site_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Holidays_site_idx" ON public."Holidays" USING btree (site);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: IDX_session_expire; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "IDX_session_expire" ON public.user_sessions USING btree (expire);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionItems_inspectionId_equipmentName_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "InspectionItems_inspectionId_equipmentName_key" ON public."InspectionItems" USING btree ("inspectionId", "equipmentName");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionItems_inspectionId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "InspectionItems_inspectionId_idx" ON public."InspectionItems" USING btree ("inspectionId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionScheduleTemplates_factoryId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "InspectionScheduleTemplates_factoryId_idx" ON public."InspectionScheduleTemplates" USING btree ("factoryId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionScheduleTemplates_factoryId_month_equipmentName_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "InspectionScheduleTemplates_factoryId_month_equipmentName_key" ON public."InspectionScheduleTemplates" USING btree ("factoryId", month, "equipmentName");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionScheduleTemplates_factoryId_month_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "InspectionScheduleTemplates_factoryId_month_idx" ON public."InspectionScheduleTemplates" USING btree ("factoryId", month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionTemplates_teamId_month_displayOrder_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "InspectionTemplates_teamId_month_displayOrder_idx" ON public."InspectionTemplates" USING btree ("teamId", month, "displayOrder");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionTemplates_teamId_month_equipmentName_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "InspectionTemplates_teamId_month_equipmentName_key" ON public."InspectionTemplates" USING btree ("teamId", month, "equipmentName");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionTemplates_teamId_month_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "InspectionTemplates_teamId_month_idx" ON public."InspectionTemplates" USING btree ("teamId", month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: MonthlyApproval_approverId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "MonthlyApproval_approverId_idx" ON public."MonthlyApproval" USING btree ("approverId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: MonthlyApproval_approverId_status_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "MonthlyApproval_approverId_status_idx" ON public."MonthlyApproval" USING btree ("approverId", status);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: MonthlyApproval_teamId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "MonthlyApproval_teamId_idx" ON public."MonthlyApproval" USING btree ("teamId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: MonthlyApproval_teamId_year_month_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "MonthlyApproval_teamId_year_month_key" ON public."MonthlyApproval" USING btree ("teamId", year, month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: MonthlyInspectionDays_factoryId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "MonthlyInspectionDays_factoryId_idx" ON public."MonthlyInspectionDays" USING btree ("factoryId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: MonthlyInspectionDays_factoryId_month_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "MonthlyInspectionDays_factoryId_month_idx" ON public."MonthlyInspectionDays" USING btree ("factoryId", month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: MonthlyInspectionDays_factoryId_month_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "MonthlyInspectionDays_factoryId_month_key" ON public."MonthlyInspectionDays" USING btree ("factoryId", month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: NoticeReads_noticeId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "NoticeReads_noticeId_idx" ON public."NoticeReads" USING btree ("noticeId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: NoticeReads_noticeId_userId_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "NoticeReads_noticeId_userId_key" ON public."NoticeReads" USING btree ("noticeId", "userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: NoticeReads_readAt_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "NoticeReads_readAt_idx" ON public."NoticeReads" USING btree ("readAt");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: NoticeReads_userId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "NoticeReads_userId_idx" ON public."NoticeReads" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Notice_authorId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Notice_authorId_idx" ON public."Notice" USING btree ("authorId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Notice_category_createdAt_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Notice_category_createdAt_idx" ON public."Notice" USING btree (category, "createdAt");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Notice_category_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Notice_category_idx" ON public."Notice" USING btree (category);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Notice_createdAt_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Notice_createdAt_idx" ON public."Notice" USING btree ("createdAt");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: PasswordResetToken_token_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "PasswordResetToken_token_idx" ON public."PasswordResetToken" USING btree (token);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: PasswordResetToken_token_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "PasswordResetToken_token_key" ON public."PasswordResetToken" USING btree (token);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: PasswordResetToken_userId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "PasswordResetToken_userId_idx" ON public."PasswordResetToken" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ReportDetails_authorId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ReportDetails_authorId_idx" ON public."ReportDetails" USING btree ("authorId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ReportDetails_itemId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ReportDetails_itemId_idx" ON public."ReportDetails" USING btree ("itemId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ReportDetails_reportId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ReportDetails_reportId_idx" ON public."ReportDetails" USING btree ("reportId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ReportDetails_reportId_itemId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ReportDetails_reportId_itemId_idx" ON public."ReportDetails" USING btree ("reportId", "itemId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ReportSignatures_memberId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ReportSignatures_memberId_idx" ON public."ReportSignatures" USING btree ("memberId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ReportSignatures_reportId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ReportSignatures_reportId_idx" ON public."ReportSignatures" USING btree ("reportId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ReportSignatures_userId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "ReportSignatures_userId_idx" ON public."ReportSignatures" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: SafetyInspections_teamId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "SafetyInspections_teamId_idx" ON public."SafetyInspections" USING btree ("teamId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: SafetyInspections_teamId_year_month_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "SafetyInspections_teamId_year_month_idx" ON public."SafetyInspections" USING btree ("teamId", year, month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: SafetyInspections_teamId_year_month_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "SafetyInspections_teamId_year_month_key" ON public."SafetyInspections" USING btree ("teamId", year, month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: SafetyInspections_year_month_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "SafetyInspections_year_month_idx" ON public."SafetyInspections" USING btree (year, month);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: SimpleEmailConfigs_emailType_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "SimpleEmailConfigs_emailType_idx" ON public."SimpleEmailConfigs" USING btree ("emailType");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: SimpleEmailConfigs_emailType_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "SimpleEmailConfigs_emailType_key" ON public."SimpleEmailConfigs" USING btree ("emailType");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: SimpleEmailConfigs_enabled_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "SimpleEmailConfigs_enabled_idx" ON public."SimpleEmailConfigs" USING btree (enabled);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TeamEquipments_teamId_equipmentName_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "TeamEquipments_teamId_equipmentName_key" ON public."TeamEquipments" USING btree ("teamId", "equipmentName");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TeamEquipments_teamId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "TeamEquipments_teamId_idx" ON public."TeamEquipments" USING btree ("teamId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TeamMembers_teamId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "TeamMembers_teamId_idx" ON public."TeamMembers" USING btree ("teamId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TeamMembers_teamId_isActive_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "TeamMembers_teamId_isActive_idx" ON public."TeamMembers" USING btree ("teamId", "isActive");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TeamMembers_userId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "TeamMembers_userId_idx" ON public."TeamMembers" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TeamMembers_userId_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "TeamMembers_userId_key" ON public."TeamMembers" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Teams_factoryId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "Teams_factoryId_idx" ON public."Teams" USING btree ("factoryId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: TemplateItems_templateId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "TemplateItems_templateId_idx" ON public."TemplateItems" USING btree ("templateId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: UserAssessment_courseId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "UserAssessment_courseId_idx" ON public."UserAssessment" USING btree ("courseId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: UserAssessment_userId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "UserAssessment_userId_idx" ON public."UserAssessment" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: UserProgress_courseId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "UserProgress_courseId_idx" ON public."UserProgress" USING btree ("courseId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: UserProgress_userId_courseId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "UserProgress_userId_courseId_idx" ON public."UserProgress" USING btree ("userId", "courseId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: UserProgress_userId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "UserProgress_userId_idx" ON public."UserProgress" USING btree ("userId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: User_email_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "User_email_key" ON public."User" USING btree (email);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: User_role_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "User_role_idx" ON public."User" USING btree (role);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: User_role_site_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "User_role_site_idx" ON public."User" USING btree (role, site);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: User_site_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "User_site_idx" ON public."User" USING btree (site);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: User_teamId_idx; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE INDEX "User_teamId_idx" ON public."User" USING btree ("teamId");');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: User_username_key; Type: INDEX; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('CREATE UNIQUE INDEX "User_username_key" ON public."User" USING btree (username);');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: AbsenceRecords AbsenceRecords_memberId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."AbsenceRecords"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "AbsenceRecords_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES public."TeamMembers"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: AbsenceRecords AbsenceRecords_reportId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."AbsenceRecords"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "AbsenceRecords_reportId_fkey" FOREIGN KEY ("reportId") REFERENCES public."DailyReports"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests ApprovalRequests_approverId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."ApprovalRequests"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "ApprovalRequests_approverId_fkey" FOREIGN KEY ("approverId") REFERENCES public."User"(id) ON UPDATE CASCADE ON DELETE RESTRICT;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests ApprovalRequests_reportId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."ApprovalRequests"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "ApprovalRequests_reportId_fkey" FOREIGN KEY ("reportId") REFERENCES public."MonthlyApproval"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ApprovalRequests ApprovalRequests_requesterId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."ApprovalRequests"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "ApprovalRequests_requesterId_fkey" FOREIGN KEY ("requesterId") REFERENCES public."User"(id) ON UPDATE CASCADE ON DELETE RESTRICT;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Assessment Assessment_courseId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Assessment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Assessment_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES public."Course"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment Attachment_commentId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Attachment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Attachment_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES public."Comment"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment Attachment_courseId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Attachment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Attachment_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES public."Course"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment Attachment_noticeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Attachment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Attachment_noticeId_fkey" FOREIGN KEY ("noticeId") REFERENCES public."Notice"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Attachment Attachment_reportDetailId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Attachment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Attachment_reportDetailId_fkey" FOREIGN KEY ("reportDetailId") REFERENCES public."ReportDetails"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Certificate Certificate_courseId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Certificate"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Certificate_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES public."Course"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Certificate Certificate_userId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Certificate"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Certificate_userId_fkey" FOREIGN KEY ("userId") REFERENCES public."User"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: ChecklistTemplates ChecklistTemplates_teamId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."ChecklistTemplates"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "ChecklistTemplates_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES public."Teams"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Comment Comment_authorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Comment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Comment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES public."User"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: Comment Comment_noticeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."Comment"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "Comment_noticeId_fkey" FOREIGN KEY ("noticeId") REFERENCES public."Notice"(id) ON UPDATE CASCADE ON DELETE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: DailyReports DailyReports_teamId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('ALTER TABLE ONLY public."DailyReports"');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('    ADD CONSTRAINT "DailyReports_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES public."Teams"(id) ON UPDATE CASCADE;');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('-- Name: InspectionItems InspectionItems_inspectionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -');
INSERT INTO "UserProgress" ("id", ""userId"", ""courseId"", "progress", "completed", ""currentStep"", ""timeSpent"", ""lastAccessed"") VALUES ('--');